# This workflow will run tests using node and then publish a package to GitHub Packages when a release is published
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages
# Rerefence https://michaelzanggl.com/articles/github-actions-cd-setup/

name: npm-publisher

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: git config --global user.name "CD Bot"
      - run: git config --global user.email "bot@guicarvalho.com.br"
      - run: npm version ${{ github.event.release.tag_name }}
      - run: npm run build
      - run: npm test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
