name: pull-request-analyser

on:
  pull_request:
  push:
    branches: 
      - master

jobs:
  test:
    name: Running Linter & Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
    - name: Apply Linter
      run: npm run lint
    - name: Run Tests
      run: npm test
